language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t abiguet/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true abiguet/docker-react npm run test